ALTER SESSION SET CONTAINER=tasksdb;

CREATE TABLE filab.tasks (
    id NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    status VARCHAR2(20),
    due_date DATE
);

CREATE INDEX tasks_status_in ON FILAB.TASKS(STATUS);
CREATE INDEX tasks_title_desc_in ON FILAB.TASKS(TITLE, DESCRIPTION);
CREATE INDEX tasks_status_title_desc_in ON FILAB.TASKS(STATUS, TITLE, DESCRIPTION);
